default_context:
  network_name: "testnet" # You MUST choose the right network
  region: "us-east-1" # Not all regions have all the instance types available.  Choose wisely
  account_id: "589796131450" # Specific account ID. If you have keys exported run `aws sts get-caller-identity | jq -r .Account`
  namespace: "icon"
  environment: "ci"
  owner: "insight"
  local_public_key: "/usr/local/icon/id_rsa.pub" # Full paths here. You need to have ssh keys on your machine.
  local_private_key: "/usr/local/icon/id_rsa"
  domain_name: "" # You have to have domain in AWS to input this option
  corporate_ip: ""  # Leave blank if you want to leave ssh port open to world
  keystore_path: "/usr/local/icon/keystore"
  keystore_password: "testing1."
  instance_type: "t3.small"
  ebs_volume_size: 30
  root_volume_size: 15
  ansible_hardening_enabled: false # This option will skip hardening steps that take additional 30 minutes to run
