version: 2.1

jobs:
  build:
    docker:
      - image: insightinfrastructure/terragrunt-aws-ci:latest
    steps:
      - checkout
      - run:
          name: clone all dependencies
          command: |
            pip install fire 
            make clone-all
      - run:
          name: Apply module
          command: |
            ssh-keygen -b 2048 -t rsa -f ./id_rsa -q -N ""
            wget https://prep-registration-helped-reindeer.s3.amazonaws.com/ci/config.yaml
            wget https://prep-registration-helped-reindeer.s3.amazonaws.com/ci/keystore
            make configs-from-config 
            make eip-register
            make apply-network
            make apply-prep-module-vpc
            ./test/test-prep-module.sh
      - run:
          name: Destroy module
          command: |
            make destroy-prep-module-vpc
            make destroy-network
      - run:
          name: Destroy on failure
          command: |
            wget https://github.com/gruntwork-io/cloud-nuke/releases/download/v0.1.13/cloud-nuke_linux_amd64 -O ./cloud-nuke
            chmod +x ./cloud-nuke
            ./cloud-nuke aws --force 
          when: on_fail
